### ISSUE TITLE
duplicate sources of truth for users on devices

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#21]
currently, our devices are using duplicate sources of truth for users and their various access rights

the device object has both a `users` key, as well as an `access` key with user ids nested

 - [ ] determine how the `users` key is being used, and see if we can deprecate it and only use the `access` key
 - [ ] remove all usage of the plain top level `users` key in all apps if this is the solution

**Comment by vdiezel** [comment]
This was closed by PR #61
