### ISSUE TITLE
deprecate catch alls for unhandled errors

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#23]
currently, the implemented pattern is to catch all errors in the hambda services. [See this file/line, for example.](https://github.com/ospin-web-dev/hambda/blob/master/services/device/src/command/nextPhase.js#L23)

[ideally, we would move away from catching all, and let our server correctly blow up and propagate an error when something goes wrong (the implication being, that an error we didn't expect to happen happened, and we need to change the code)](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-mode-exceptions.html)

this way, bugs are fixed in the code base, and unhandled errors become handled errors where we can either fix what's breaking, or provide meaningful 3xx/4xx responses to the requestor

Remove the catch alls from all of our services' commands and actions 

~perhaps best completed _after_ #22~ (this has been completed)

**Comment by vdiezel** [comment]
this was fixed by implementing middy error handling middleware
