### ISSUE TITLE
Hambda CD 5: CD for cortex service

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/hambda#282]
The new cortex service can already be deployed using the cli. Now we need to implement it into our CD pipeline for hambda when code changes are recognized in cortex ( or lib?)

**Comment by DanielSeehausen** [comment]
## Deliverables
- [ ] circle ci must identify changes within cortex vs. changes within lambda services
- [ ] if a change is present in cortex, then in addition to anything else this CD is doing, cortex is also deployed
- [ ] separate messaging should be used for our circle-ci channel

**Comment by vdiezel** [comment]
This has been done.
