### ISSUE TITLE
Hambda CD 3: Ensure all alert systems are working - update Datadog

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#329]
## Deliverables
- [ ] ensure/implement all alert/monitoring systems for staging 
  - lambdog
  - circle-ci channel
  - datadog dashboards
  - lobotomy requests channel
  - anything else?

**Comment by vdiezel** [comment]
- Lambdog alarms don't need any changes. 
- circleCI-slack channel is notified via CD suite of hambda now
- dashboard for Cortex augmented with the new staging instance
- added alarm for the staging environment for cortex to datadog to lobotomy requests
- dashboards for MongoDB and lambda don't need any changes
