### ISSUE TITLE
Test Flicker in `device/list`

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#335]
[as mentioned here](https://github.com/ospin-web-dev/hambda/pull/332)

this test seems to be flickering!

![image](https://user-images.githubusercontent.com/17087405/77741310-faf15c00-7014-11ea-9326-e489d5db03f5.png)

**Comment by O-Susanoo** [comment]
Closing this issue for three reasons : 

- after testing it multiple times nothing happens

- Before tests weren't running correctly so if it was an issue it should have been caught already

- the flickering tests themselves are not the same anymore
