### ISSUE TITLE
Add git hook to warn on push on failing tests

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#386]
related to: ospin-web-dev/reactor#654
Whoever picks this up should probably do/pair on both!

Currently, our CI/CD encourages pushing and not knowing if code is failing tests until it runs on CircleCI in PRs. 

This ticket is the interest of saving circleCI run time and developer time (as tests are quicker locally, other devs can't review code properly that is broken because its going to get an update, and its quicker to fail fast and fix rather than see it on github)

### Deliverables
(There may be other better local options, but I'll write down the only one that comes to mind that I know of)
- [x] add a git hook that, when a someone pushes, runs tests beforehand and only pushes after the developer has passed
- [x] if its simple, let the developer override a failure report and say 'push anyways'. Maybe git has a built in key command thing for this?
- [x] if its simple, we could invert this, and instead when someone pushes prompt them with a 'do you want to run tests before you push?'. This might be preferable and give the control to the developer, while still providing the reminder

https://www.npmjs.com/package/husky looks like the major library for this at >3m downloads a week

**Comment by vdiezel** [comment]
see here: 
https://github.com/ospin-web-dev/REACTor/issues/654
Only difference is the test command!
```bash
#!/bin/sh

# Read user input, assign stdin to keyboard
exec < /dev/tty

status=$?
while read -p "Do you want to run tests before execution? (Y/n) " yn; do
    case $yn in
        [Yy] ) npm run testAll; status=$? && break;;
        [Nn] ) break;;
        * ) echo "Please answer y (yes) or n (no):" && continue;
    esac
done

if [ $status -eq 0 ]
then
  echo "Executing command!"
  exit 0
else
  while read -p "Tests failed. Do you want to execute nevertheless? (Y/n) " yn; do
      case $yn in
          [Yy] ) break;;
          [Nn] ) exit 1;;
          * ) echo "Please answer y (yes) or n (no):" && continue;
      esac
  done
fi
```
