### ISSUE TITLE
Change events so firmware can close events!

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#387]
### Description

Denis/firmware requested some changes to the way events are closed.
Currently, events are deleted when they have a name that automatically resolves other events (see `EventRevoker` and how it is used through the device trigger `createEvent`)

They would like to be able to close events via an additional key on the createEvent payload.

---

### Deliverable(s)
- [ ] write tests to ensure events created with `revokeEvents: [<eventName>, <eventName>]` properly revokes events
- [ ] update event payloads with a `revokeEvents` key:
```js
// something like:
revokeEvents: Joi.array().items(Joi.string()).default([]),
```
- [ ] update endpoints to validate, accept, and handle this accurately
- [ ] remove the event recocation map and its usage throughout the code base entierly, as it is no longer required

Note: some older events won't have this key, so we need safe navigation wherever `revokeEvents` is being used

**Comment by dgrafov** [comment]
Regarding the autoresolving part: 
emergencyStopPressed / emergencyStopReleased have the same semantics as doorOpen / doorClosed
however it's not yet clear for the rest. Please follow up on that before starting to implement.

**Comment by DanielSeehausen** [comment]
> Regarding the autoresolving part:
> emergencyStopPressed / emergencyStopReleased have the same semantics as doorOpen / doorClosed
> however it's not yet clear for the rest. Please follow up on that before starting to implement.

changed per discussion to move event revoking to your end
