### ISSUE TITLE
Improve test coverage on the `listUserDevices` endpoint in the user service

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/hambda#401]
implement the test coverage to prevent the bug described here: #399 

A test should exists for this endpoint which should break when the UIConfig Model is not connected to the database.

**Comment by DanielSeehausen** [comment]
just confirmed this is fixed now! Believe it was when I updated the test suite to use connectAll separately from the seeder (good recommendation to separate those @vdiezel )

![image](https://user-images.githubusercontent.com/17087405/83075819-c7629a80-a074-11ea-8a9e-37820b979a01.png)
