### ISSUE TITLE
Add some events for firmware

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#411]
### Description

Denis/firmware requested extending some accepted events from the device

---

### Deliverable(s)
- [ ] add the following to the event mapping in the event model
- [ ] once complete (aka merged and deployed), follow up with @dgrafov to let him know it has been incorporated

```
emergencyStopPressed
filterHeaterOn
filterHeaterOff
platformTempHigh
platformTempLow
bagTempLimitReached
```

**Comment by vdiezel** [comment]
This is not necessary anymore because now the firmware get full control over events.
