### ISSUE TITLE
Change db password

### ISSUE THREAD

**Issue by O-Susanoo** [ospin-web-dev/hambda#419]
In case we want to change db password we have a problem because there is no clear procedure on how to do it. one may think that we could change the env file and redeploy which is totally possible but we may lose data , so either we change how we access credentials so that we can change a running environment without having to deploy nothing 
[Example](https://www.concurrencylabs.com/blog/configure-your-lambda-function-like-a-champ-sail-smoothly/)
, or we can deploy in this order
process
cortex
device
event
eventTrigger
user
utils
log
uIConfig
configurator

i guess this order is the one with the least damage

**Comment by DanielSeehausen** [comment]
closing this issue as mo provided documentation in the wiki and we decided not to change password for the time being
