### ISSUE TITLE
Fetching Device Processes Speed Up

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#425]
### Description
Ever increasing amount of processes is slowing down the user experience in the web application when we fetch device processes. (almost 10 seconds on celltainer when I tried just now! Some of that may be from a lambda cold start)

related to: ospin-web-dev/REACTor#651

---

### Proposed Solution(s)
There are several things we can do to improve this experience (fetching more processes on scroll/pagination), but I am only proposing to do one right now:

Analyze where in our backend/the network communication the slow down is in GET device processes (is it in the mongo call, is it the size of the response getting to the client, is it something else?)

Optimize the device processes look up depending on where the slow down is caused.

One direction this might need to go (if it's a response size issue) is to send light process data when we fetch device processes. This will require investigation on the front end to ensure everything still works as intended, and that whenever a /device/id/process/id route is hit, that the whole process is loaded.

If front end work is required, update this ticket with the required work!:
ospin-web-dev/REACTor#651

---

### Deliverable(s)
As a user:
Given how many processes devices on dev have right now,
fetching device processes is a faster operation than it is now

This does not include a pagination implementation!

---

![image](https://user-images.githubusercontent.com/17087405/80975155-0577f000-8e22-11ea-8641-b8961970f944.png)

===== Update ===== 
the end point should return this fields 

```
{
  id,
  name,
  comment,
  createdAt,
  createdBy,
  cloneHistory,
  access,
  pinned,
  ownerId,
  startedAt,
  startedBy,
  finishedAt,
}
```

**Comment by O-Susanoo** [comment]
when we load a process list each process is full which mean that each process contain the following properties :
```
{
    "id":"",
    "deviceId":"",
    "createdAt":1588764586799,
    "createdBy":"",
    "name":"P30 I 0.5",
    "pinned":false,
    "cloneHistory":[
    ],
    "description":{
    },
    "entryPhaseId":0,
    "progression":[
    ],
    "comment":"",
    "ownerId":"",
    "deviceDescription":[
    ],
    "access":[
       {
          "name":"admins",
          "rights":"11111",
          "users":[
             ""
          ]
       },
       {
          "name":"operators",
          "rights":"11100",
          "users":[
          ]
       },
       {
          "name":"viewers",
          "rights":"10000",
          "users":[
          ]
       }
    ],
    "startedBy":"",
    "startedAt":1588764631315,
    "finishedAt":null,
    "eventTriggers":{
    },
    "updatedAt":1588764629068
 }

```

most of the data size is in description & deviceDescription the goal is to have this object at the end

```
{
    "id":"",
    "createdAt":1588764586799,
    "createdBy":"",
    "name":"P30 I 0.5",
    "pinned":false,
    "comment":"",
    "ownerId":"",
    "access":[
       {
          "name":"admins",
          "rights":"11111",
          "users":[
             ""
          ]
       },
       {
          "name":"operators",
          "rights":"11100",
          "users":[
          ]
       },
       {
          "name":"viewers",
          "rights":"10000",
          "users":[
          ]
       }
    ],
    "startedBy":"",
    "startedAt":1588764631315,
    "finishedAt":null,
    "updatedAt":1588764629068
 }

```
