### ISSUE TITLE
H3: Clone a virtual device for each new demo account

### ISSUE THREAD

**Issue by ConorTighe1995** [ospin-web-dev/hambda#434]
### Description
When a demo user is created they will automatically be an admin on a virtual device

---

### Proposed Solution(s)
Use the device model to clone a new virtual device based off a pre-existing device in the database. This device will always be online and needs to be added to the dev team accounts for testing. `isVirtual` should be true, this flag will be later used by the front end to stop breaking requested made to the backend by intercepting the request if this is true.

BLOCKED BY: #433 
---

### Deliverable(s)
- [ ] Create an ideal virtual device (something with all the cool streams and non of the client specific ones like celltainer's bag stuff. It should be marked as virtual and as `online` and `idle`)
  **Note:** we will also want to grab a nice finished process (with clean and good looking data in the datagraphs) to use as a sample process on the demo device. Because of this, consider cloning a device (maybe celltainer/FU/w/e), and getting rid of those streams we don't want'/wont look the best. We can then selectively remove those streams we don't want since this is all virtual.
- [ ] On user demo account creation add that account to the device
- [ ] The account should be a **operator** on the device.

Note: these devices are USER specific. the ideal device is cloned so that one demo device is not shared among users!

tests!

**Comment by DanielSeehausen** [comment]
https://github.com/ospin-web-dev/hambda/compare/434-clone-virtual-device?expand=1

WIP branch - lots to do here with abstracting a device, adding tests, etc.
