### ISSUE TITLE
H6: Stale demo accounts are deleted.

### ISSUE THREAD

**Issue by ConorTighe1995** [ospin-web-dev/hambda#437]
### Description
Demo accounts will build up over time with cognito and mongo getting filled with unused data. We need a way to clear these out manually or ideally automatically.

---

### Proposed Solution(s)
 A script might be needed here that runs based on a timestamp or heuristic value.

---

### Deliverable(s)
- [ ] Stop stale user accounts from building up

**Comment by O-Susanoo** [comment]
We need to use the cloudwatch schedule to call a lambda function that will delete all demo users every day or so

![image](https://user-images.githubusercontent.com/57438770/82347626-689f8000-99e7-11ea-8ad6-4ef63736e5df.png)
